### ISSUE TITLE
Problema con la eliminación del índice

### ISSUE THREAD

**Issue by BenEspinoza10** [Template-Latex/Template-Informe#10]
Quiero eliminar todos los índices que se generan, pero con el \showindexofcontents{false},  sólo se elimina el de índices, hay algún comando que se deba agregar en el template_config para que funcione?

**Comment by ppizarror** [comment]
Hola, tienes dos métodos para borrar el índice:

1. borrar \templateIndex del main.tex
2. definir \def\indexstyle {}  y  \showindexofcontents{false}
