### ISSUE TITLE
Error en subtítulo

### ISSUE THREAD

**Issue by bunitram** [Template-Latex/Template-Informe#12]
En el template del informe, cuando se llena la función de \def\documentsubtitle {} en la portada, este lanza un error y al compilar el subtítulo es cargado una página antes de la portada.

**Comment by ppizarror** [comment]
Ciertamente, corregí el error en la nueva versión. gracias

**Comment by bunitram** [comment]
Muchas gracias!!!!

**Comment by ppizarror** [comment]
Creo que el error fue producto de alguna librería que se actualizó (me imagino el de los operadores lógicos como if/else) ya que hace unos pocos meses funcionaba bien. Template informe, reporte, tesis y artículo fueron hoy actualizados. saludos
