### ISSUE TITLE
package subcaption no funciona

### ISSUE THREAD

**Issue by antoniacaviedes** [Template-Latex/Template-Informe#13]
Hola, primero que nada muchas gracias por el template. Tuve un problema tratando de usar la finción subtable que encontré en [esta página](https://www.overleaf.com/learn/latex/How_to_Write_a_Thesis_in_LaTeX_(Part_3)%3A_Figures%2C_Subfigures_and_Tables#Tables). Requiere la librería subcaption, como no está en la lista de librerías la incluí despues de \input{template}, pero luego no reconoce la función subtable. 

Traté de meterme al código del template e incorporarla a la lista de librerías independientes, eso soluciona el problema y funcionan las subtables, pero se descativa el índice (el índice de tablas y figuras queda vacío). Agradezco cualquier ayuda!

**Comment by ppizarror** [comment]
Problema solucionado en la nueva ``v8.2.0``. Saludos!
