### ISSUE TITLE
Error código informe.tex en \lstdefinestyle{perl}

### ISSUE THREAD

**Issue by gbalfa** [Template-Latex/Template-Informe#3]
Línea 212
\lstdefinestyle{perl}{language=Perl,aboveskip=3mm,alsoletter={\backgroundcolor=\color{backcolour},....
"alsoletter={" sin elementos y abierto.

**Comment by ppizarror** [comment]
Gracias por publicar este error, no lo había reconocido al compilar con pdflatex de manera automática. Ya fue reparado, lo que paso es que se reconocia \% como un comentario eliminando la línea:

https://github.com/Template-Latex/Export-Subtemplate/commit/3e6bfa5a5f865f6bfb0cecd83793d3853d5b7019

Ya fue reparado.
Saludos
