### ISSUE TITLE
Tikz y table enuna sola linea

### ISSUE THREAD

**Issue by sesepulveda17** [Template-Latex/Template-Informe#4]
Hola, siguiendo la sugerencia de publicar aquí, quería consultar qué método se recomienda para que una tabla hecha con el entorno tabular esté en la misma linea que un dibujo del mismo tamaño hecho en tikz. Porque lo que me pasa es que latex hace un salto de linea entre cada uno.
No me dan ganas de extraerlos como imágenes y hacer soluciones parche con include graphixs, por eso mi duda :(. jajaja. 

Gracias de antemano
Saludos

**Comment by ppizarror** [comment]
Una alternativa es hacer algo como

\begin{minipage}[l]{0.5\textwidth}
		TU TABLA
\end{minipage}
\begin{minipage}[r]{0.5\textwidth}
	TU FIGURA
\end{minipage}

Con eso haces dos minipage, le das mitad a c/u y te queda en "una sola línea"
ahi tienes que jugar con las proporciones, puede ser .3 / .7, o algo x el estilo

**Comment by sesepulveda17** [comment]
por mucho que cambie valores, y achique los dibujos no logro que estén en la misma linea :((( Aqui el codigo:

\begin{minipage}[l]{0.2\textwidth}
\begin{tikzpicture}[level distance=1.3cm,
   level 1/.style={sibling distance=6cm, level distance=1cm},
   level 2/.style={sibling distance=3cm, level distance=1cm},
   level 3/.style={sibling distance=1.5cm, level distance=1cm}]%Se ocupo para poder separar el arbol creado en una distancia dada
\tikzstyle{every node}=[circle,fill=red!30, inner sep=0pt,minimum size=9mm, node distance=0.5pt]% define el cómo será cada nodo
\tikzstyle{edge from parent}=[red,->,thick,draw] %define el trazado o conexion que abrá entre cada nodo
\node {$/$}%cabeza
	child {node {$4$}}
	child {node {$7$}%hijo der
};
\end{tikzpicture}
\end{minipage}

\begin{minipage}[r]{0.2\textwidth}
\begin{tabular}{|ccc|}
&  & \\ \hline
& 3 & \\ \hline 
& x & \\ \hline
& 2 & \\ \hline
\end{tabular}
\end{minipage}

**Comment by ppizarror** [comment]
intenta enviarme algun sharelatex o algo por el estilo, no sé que librerías importaste, así me es más facil editar y ver si es un bug o algo asi

**Comment by sesepulveda17** [comment]
Hecho 👍

**Comment by ppizarror** [comment]
Ahi lo arreglé, quedaría algo así:

\begin{table}[H]
\begin{minipage}[b]{0.2\linewidth}\centering
\begin{tikzpicture}[level distance=1.3cm,
   level 1/.style={sibling distance=6cm, level distance=1cm},
   level 2/.style={sibling distance=3cm, level distance=1cm},
   level 3/.style={sibling distance=1.5cm, level distance=1cm}]%Se ocupo para poder separar el arbol creado en una distancia dada
\tikzstyle{every node}=[circle,fill=red!30, inner sep=0pt,minimum size=9mm, node distance=0.5pt]% define el cómo será cada nodo
\tikzstyle{edge from parent}=[red,->,thick,draw] %define el trazado o conexion que abrá entre cada nodo
\node {$/$}%cabeza
	child {node {$4$}}
	child {node {$7$}%hijo der
};
\end{tikzpicture}
\end{minipage}
\hspace{7cm} % Cambiar este espacio
\begin{minipage}[b]{0.2\linewidth}
\centering
\begin{tabular}{|ccc|}
&  & \\ \hline
& 3 & \\ \hline 
& x & \\ \hline
& 2 & \\ \hline
\end{tabular}
\end{minipage}
\end{table}

La solución era usar una tabla en vez de un minipage, https://texblog.org/2007/08/01/placing-figurestables-side-by-side-minipage/

**Comment by ppizarror** [comment]
Se me ocurrió además crear una función del estilo

\createtwocolumn{0.2}{0.2}{7cm}{ 

\begin{tikzpicture}[level distance=1.3cm,
level 1/.style={sibling distance=6cm, level distance=1cm},
level 2/.style={sibling distance=3cm, level distance=1cm},
level 3/.style={sibling distance=1.5cm, level distance=1cm}]%Se ocupo para poder separar el arbol creado en una distancia dada
\tikzstyle{every node}=[circle,fill=red!30, inner sep=0pt,minimum size=9mm, node distance=0.5pt]% define el cómo será cada nodo
\tikzstyle{edge from parent}=[red,->,thick,draw] %define el trazado o conexion que abrá entre cada nodo
\node {$/$}%cabeza
child {node {$4$}}
child {node {$7$}%hijo der
};
\end{tikzpicture}

}{

\begin{tabular}{|ccc|}
& & \ \hline
& 3 & \ \hline
& x & \ \hline
& 2 & \ \hline
\end{tabular}

}

**Comment by ppizarror** [comment]
Básicamente la función hace lo mismo que el código que hice, pero más simplificado

**Comment by sesepulveda17** [comment]
ooh, esta muy bueno, muchas gracias!!!

**Comment by ppizarror** [comment]
mira el documento, despues de algunas horas de trabajo hice algunas funciones para crear columnas, inventé varias

puedes revisarlas y probar varios casos?
gracias

**Comment by ppizarror** [comment]
el detalle del nuevo archivo lo puedes ver en column.tex, está en la raíz de la carpeta

**Comment by sesepulveda17** [comment]
perfect lo revisaré mientras

**Comment by ppizarror** [comment]
eres libre también de proponer o hacer cambios 😄
